### PR TITLE
pin prysm to non-branch commit: 0893821e35e7

### PR DESCRIPTION
**Pull request by kasey**
@karalabe @MariusVanDerWijden 

The previous PR was pointed at a commit in a branch which got destroyed on merge. This updates the pinned version to a commit in prysm's main develop branch post-merge.

### CODE REVIEW

**Comment by kasey** [comment]
I missed Marius' PR - deleting this one.

**Comment by karalabe** [comment]
Can we get this repor fixed in the mean time somehow?

**Comment by kasey** [comment]
> Can we get this repor fixed in the mean time somehow?

Sorry for miscommunication - I approved and merged Marius' fix right after I commented here, at which point I was able to build spectests and run them. Can you verify if that solved your problem, or was there another issue?

**Comment by karalabe** [comment]
It's ok, was fixed via https://github.com/prysmaticlabs/prysm/pull/12098 and https://github.com/OffchainLabs/methodical-ssz/pull/11. Thx

**Pull request closed without merging**
