### PR TITLE
Pin prysm with fix for incongruous build tag / go.mod 1.19

### PR DESCRIPTION
**Pull request by kasey**
The go version in go.mod was upgraded to go 1.20, which broke the generated spectest code. @MariusVanDerWijden was probably unable to run the spectest code and notice this issue because the yaml fixture was missing.

This PR adds the missing yaml fixture and pins a branch on prysm that fixes the issue created by prysm including some 1.20-only code under a `go1.20` build tag, while also specifying the module version as 1.20. It is fine for geth to build at 1.19 and use a 1.20 dependency, but when using a 1.20 compiler, the inclusion 1.20-only code in a module marked as 1.19 causes a compiler validation failure. This update pins the prysm version to a branch where this inconsistency in prysm is fixed. We can update the pin at prysm mainline when that is merged in.

prysm PR here https://github.com/prysmaticlabs/prysm/pull/12084.

### CODE REVIEW

**Review by MariusVanDerWijden — APPROVED** [review]
Sgtm

**Comment by karalabe** [comment]
Something's borked, `go list` fails after this PR anf such Goland IDE cannot operate on this project any more:

```
$ go list -m -json -mod=mod all
go: github.com/MariusVanDerWijden/tx-fuzz@v0.0.0-00010101000000-000000000000: invalid version: unknown revision 000000000000
```

**Comment by karalabe** [comment]
Myeah https://github.com/prysmaticlabs/prysm/commit/af0dee34

> This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

This hack will probably only work on your machine where this commit exists

**Comment by karalabe** [comment]
Seems this wasn't the issue, rather the tagged version has 3 `replace` statements in Go, which are no-nos for using as a dependency :/

https://github.com/prysmaticlabs/prysm/blob/develop/go.mod#L263

The worst offender is however this ^ one replace, because it also swapped the version of tx-fuzz to 0

https://github.com/prysmaticlabs/prysm/blob/develop/go.mod#L8

That needs to be changed back, though in reality all 3 replaces should go

**Comment by kasey** [comment]
Oops, I think the issue the prysm branch was merged and the pinned branch+commit got deleted, will fix.

**Pull request merged**
